### ISSUE TITLE
Pagina 404

### ISSUE THREAD

**Issue by jforni** [SDanielP/FinalProyectRolling-Sangre-Criolla#20]
Cuando me redirige a la página 404, en realidad en el deployado me lleva a página no encontrada.
Adjunto imagen:
![image](https://github.com/SDanielP/FinalProyectRolling-Sangre-Criolla/assets/6042663/38c9cdca-07eb-470f-87b1-ea0618430176)

**Comment by Ana-Kuenneth** [comment]
Se corrigió la redirección a la página 404 de los links que no tienen implementación específica.

Sin embargo vemos que el netlify por ahí falla con la carga de las páginas y tira la página de error de netlify. Si hay algo más para corregir sobre esto estamos atentos 🙂

**Comment by SDanielP** [comment]
se soluciono el error en netlify, agreando una carpeta public en la raiz con un archivo _redirects y una linea de codigo
