### ISSUE TITLE
Permite enviar un formulario vacío

### ISSUE THREAD

**Issue by jforni** [SDanielP/FinalProyectRolling-Sangre-Criolla#21]
Al formulario de contacto me lo permite enviar vacío
Adjunto imagen:
![image](https://github.com/SDanielP/FinalProyectRolling-Sangre-Criolla/assets/6042663/05c35e9d-4aaf-4d2e-8e7d-cf74245b469c)

**Comment by jmurzagasti** [comment]
el formulario ya no se puede enviar vacío
