### ISSUE TITLE
Formulario de contacto sin validaciones

### ISSUE THREAD

**Issue by jforni** [SDanielP/FinalProyectRolling-Sangre-Criolla#22]
El formulario de contacto no tiene validaciones
Adjunto imagen:
![image](https://github.com/SDanielP/FinalProyectRolling-Sangre-Criolla/assets/6042663/4a836865-9bc2-4b19-bcd0-ade8d2ca613b)

**Comment by jmurzagasti** [comment]
validaciones para el formulario agregadas
