### ISSUE TITLE
Mensaje de productos no encontrados poco visible

### ISSUE THREAD

**Issue by jforni** [SDanielP/FinalProyectRolling-Sangre-Criolla#23]
Cuando filtro por alguna categoría que no tiene productos, el mensaje no se ve claramente.
Adjunto imagen:
![image](https://github.com/SDanielP/FinalProyectRolling-Sangre-Criolla/assets/6042663/73cd5e34-34c7-42a1-86cc-f46d924e16d7)

**Comment by Ana-Kuenneth** [comment]
Buenas! Error corregido, ahora se pueden visualizar los mensajes de error de conexión a la api y los de la base de datos con claridad.
Ana Kuenneth

![image](https://github.com/user-attachments/assets/158cecbd-dd91-4790-b0b0-42cab437a385)
![image](https://github.com/user-attachments/assets/75b99fc6-015a-46d6-9207-8712455ed358)
