### ISSUE TITLE
Formulario de registro no se limpia

### ISSUE THREAD

**Issue by jforni** [SDanielP/FinalProyectRolling-Sangre-Criolla#24]
Una vez que realizo el registro de usuario, el formulario no se limpia.
Adjunto imagen:
![image](https://github.com/SDanielP/FinalProyectRolling-Sangre-Criolla/assets/6042663/e5dd4a42-7234-4904-94d0-4395d2171c2e)

**Comment by marukuenneth** [comment]
Buen domingo. Ya solucioné la issue! Saludos.
